services:
  sunsetbot:
    container_name: sunsetbot
    image: ghcr.io/felix2yu/sunsetbot:latest
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./config.yaml:/app/config.yaml
    restart: unless-stopped
